# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e5720d9e4af02c356da9c9395f8bbab9283485d3645850e6eac88a07b6300c9abdc44fbe5e155f9a7fa13b2f906d268c2f0b5409fe8b148cdd6f0e6805c6775

test:
  secret_key_base: a427b73c41abae3c83126fb2fd67e0995d86fbfa2ca68e573b877edd4f7f19abf49169ef7c31d7c55973de7d48b7efe99175890e3cc41fa67d74477b5ac424b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
